### ISSUE TITLE
What LICENSE does this project use?

### ISSUE THREAD

**Issue by Shivelight** [crashdemons/AztecTabCompleter#11]
Can't see it anywhere, curious if I can fork the project to suit my needs.

**Comment by crashdemons** [comment]
I'm the author, so I can license it to you under [MPL2](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) or [GPL3](https://www.gnu.org/licenses/gpl-3.0.en.html) at your option (free and open-source).
(Let me know if you require more closed, specific licensing - and the nature of that license)

No further action is necessary, since this will document it.   I do need to add license notices to the source though, depending it on the license we choose.

If the changes benefit the project as a whole, I would also entertain pull requests.

**Comment by Shivelight** [comment]
I'm not familiar with MPL2, but it seems attractive, so I guess I will go with it and will probably use it on my future projects :)

> If the changes benefit the project as a whole, I would also entertain pull requests.

I was looking for a command whitelist plugin that also filters the command suggestion/completion list, but I can't find any that works, and this project is actually close to what I need, and I only have to handle player command and do filtering. It's not a significant change, and I don't think it's within the scope of this project.

**Comment by crashdemons** [comment]
added with commit 82f64821b2e52a27f7caf523eec324857bf64807

**Comment by Shivelight** [comment]
Perfect, closing this.
