### ISSUE TITLE
[Suggestion] Adding the permissions

### ISSUE THREAD

**Issue by ArtNRG** [crashdemons/AztecTabCompleter#2]
It will be nice to add few permission-based lists of the tab-completing commands to be able to separate staff commands and common. Adding the bypass permission which will allow seeing all tab completes would be useful too.

**Comment by crashdemons** [comment]
A bypass permission has been added in d9ff0db7948514b891d4cf63d3406dd0362cec27 ([0.17.5-SNAPSHOT](https://ci.meme.tips/job/AztecTabCompleter/3/)).

I'll keep working on adding group-based whitelists.

**Comment by crashdemons** [comment]
Let me know if [0.19.1-SNAPSHOT](https://ci.meme.tips/job/AztecTabCompleter/7/artifact/target/AztecTabCompleter.jar) (current master version) works for you for group permissions.

[Example Config](https://github.com/crashdemons/AztecTabCompleter/blob/master/src/main/resources/config.yml)

Once you define groups, the permission for each is `aztectabcompleter.group.group-name-here`, and a person may have multiple in order to combine command lists.
After reloading you will need to rejoin in order for the commands packet to be resent.

This is an experimental version so there may be errors I need to fix, as well.

Note: Permission-validation filtering was removed, whitelists and blacklists remained with slightly modified behavior.

**Comment by crashdemons** [comment]
Note:  If you have "op" or the `*` permission on the server, you will also implicitly have `aztectabcompleter.bypass` and you will see all commands regardless of other settings.

**Comment by crashdemons** [comment]
It's been almost a week and 0.19.1-SNAPSHOT works for me, so I'm going to assume there's no further issues with this feature - please open issue if there are further problems.
