### ISSUE TITLE
Another one suggestion - add tabcomplete dump

### ISSUE THREAD

**Issue by ArtNRG** [crashdemons/AztecTabCompleter#4]
With the latest commit which adds an ability to set up whitelist or blacklist will be really useful to get all tab completes from the server and then just spread them between whitelist and blacklist.

And seems the plugin doesn't support UTF8 because few of my commands are not appears in a client:

 - к
 - р
 - с
 - вики
 - сс

**Comment by crashdemons** [comment]
Can you upload your current config.yml somewhere so I can try to reproduce the problem?
(a file upload - not as text, since text won't contain how it was encoded/BOM)

Right now, the default bukkit methods to read config entries are being used, I don't know if they are supposed to support UTF-8, but I would imagine so...

Can you also describe the feature you mention in the issue title a little more?  Do you just want a dump of the last Commands list from the packet? Do you want the commands from before or after filtering?

Off-topic: The blacklist and permissions-filter feature should be considered experimental at this point since it looks like group support will require significant changes to filtering logic.

**Comment by ArtNRG** [comment]
I want to get the list of all commands which can be tab completed like if I don't use the plugin. Then I want to use that list to make a config to the plugin.
My config: https://pastebin.com/raw/27KVmJx4
I use it with AztecTabCompleter version 0.17.4 (alpha)

**Comment by crashdemons** [comment]
I can't reproduce locally: [screenshot](https://i.imgur.com/8VBFGUg.png)

AZTab 0.17.4, I tested both spigot-1.13.1 and papermc 1.13.1
 (I added the command вики as an alias to be able to test it, but the origin shouldn't matter...)

Keep in mind, file encoding may matter depending on your system and environment, I'm primarily testing on windows with the config file saved as UTF8 (*with* BOM, sorry I misspoke before the edit.)

**Comment by ArtNRG** [comment]
That's odd [screenshot](https://cdn.pbrd.co/images/HIpme8B.png)

**Comment by crashdemons** [comment]
Does it show up in the initial tab list after you type `/` and hit tab?

And does it show up when you have aztab off?

**Comment by ArtNRG** [comment]
No, it isn't.

**Comment by crashdemons** [comment]
Sorry I edited my comment to ask a second question also - did it show up before using this plugin?  If it wasn't already there, this plugin won't add it - it only removes unwanted entries.

Another thing you can try is adding `-Dfile.encoding=UTF8` to your server startup command (before `-jar`) to see if it matters - otherwise I'm guessing there's some issue with how the config file was saved that bukkit doesn't like, or your environmental settings.

Another option is to test is the unicode-escape support in YAML like
`    - "foo\u2009bar"`
although I realize this is annoying to do.

**Comment by crashdemons** [comment]
I think the escaped version would be `- "\u0432\u0438\u043A\u0438"` (with proper indention) if you want to try it.

**Comment by ArtNRG** [comment]
> did it show up before using this plugin? If it wasn't already there, this plugin won't add it - it only removes unwanted entries.

Seems here is the reason. Now it will be simple to make it work, thank you.

**Comment by crashdemons** [comment]
Ah, okay.

**Comment by crashdemons** [comment]
The original feature request should be added in 4135f2126240ea68b64bab841bbc8863f8392abd  ([0.20.2 alpha of bukkit-events branch](https://ci.meme.tips/job/AztecTabCompleter-BukkitEventRework/3/))

**Comment by crashdemons** [comment]
I will note that players who have the _bypass_ permission or who do not have the _suggest_ will not trigger a dump.

A dump of commands (before and after) will occur for a normal user who receives filtered suggestions.
